apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl-appwithproxy
  labels:
    app: appwithproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appwithproxy
  template:
    metadata:
      labels:
        app: appwithproxy
    spec:
      containers:
        - name: demowebapp
          image: demowebapp
          imagePullPolicy: Never
          ports:
          - containerPort: 8080
        - name: revproxy
          image: revproxy
          imagePullPolicy: Never
          ports:
          - containerPort: 9090
          env:
          - name: "BKHOST"
            value: "http://localhost"
          - name: "BKPORT"
            value: "8080"
          - name: "AUTHHOST"
            value: "http://authsimple.com"
          - name: "AUTHPORT"
            value: "80"
          - name: "TOKENHOST"
            value: "http://svc-authsimple"
          - name: "TOKENPORT"
            value: "8585"
---
apiVersion: v1
kind: Service
metadata:
  name: svc-appwithproxy
spec:
  selector:
    app: appwithproxy
  #type: LoadBalancer
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
    #nodePort: 30000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-appwithproxy
spec:
  rules:
  - host: demowebapp.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: svc-appwithproxy
            port:
              number: 9090