apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl-demowebapp
  labels:
    app: demowebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demowebapp
  template:
    metadata:
      labels:
        app: demowebapp
    spec:
      containers:
        - name: demowebapp
          image: demowebapp
          imagePullPolicy: Never
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: svc-demowebapp
spec:
  selector:
    app: demowebapp
  #type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    #nodePort: 30000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-demowebapp
spec:
  rules:
  - host: demowebapp.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: svc-demowebapp
            port:
              number: 8080