apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl-authsimple
  labels:
    app: authsimple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authsimple
  template:
    metadata:
      labels:
        app: authsimple
    spec:
      containers:
        - name: authsimple
          image: authsimple
          imagePullPolicy: Never
          ports:
          - containerPort: 8585
---
apiVersion: v1
kind: Service
metadata:
  name: svc-authsimple
spec:
  selector:
    app: authsimple
  #type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8585
    targetPort: 8585
    #nodePort: 30001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-authsimple
spec:
  rules:
  - host: authsimple.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: svc-authsimple
            port:
              number: 8585